CREATE TABLE IF NOT EXISTS `country` (
`id` int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `name` varchar(255) NOT NULL
);

INSERT INTO country (`name`) VALUES
('Afghanistan'),
('Albania'),
('Bahamas'),
('Bahrain'),
('Cambodia'),
('Cameroon'),
('Denmark'),
('Djibouti'),
('East Timor'),
('Ecuador'),
('Falkland Islands (Malvinas)'),
('Faroe Islands'),
('Gabon'),
('Gambia'),
('Haiti'),
('Heard and Mc Donald Islands'),
('Iceland'),
('India'),
('Jamaica'),
('Japan'),
('Kenya'),
('Kiribati'),
('Lao Peoples Democratic Republic'),
('Latvia'),
('Macau'),
('Macedonia'),
('Namibia'),
('Nauru'),
('Oman'),
('Pakistan'),
('Palau'),
('Qatar'),
('Reunion'),
('Romania'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Taiwan'),
('Tajikistan'),
('Uganda'),
('Ukraine'),
('Vanuatu'),
('Vatican City State'),
('Wallis and Futuna Islands'),
('Western Sahara'),
('Yemen'),
('Yugoslavia'),
('Zaire'),
('Zambia');